//
//  Data.swift
//  Warikan
//
//  Created by nttr on 2017/10/03.
//  Copyright © 2017年 nttr. All rights reserved.
//

import Foundation

class Data {
    class func getData() -> [DateModel]{
        var data = [DateModel]()
        data.append(DateModel(price: "20,000円" ))
        data.append(DateModel(price: "20,500円" ))
        data.append(DateModel(price: "21,000円" ))
        data.append(DateModel(price: "21,500円" ))
        data.append(DateModel(price: "22,000円" ))
        data.append(DateModel(price: "22,500円" ))
        data.append(DateModel(price: "23,000円" ))
        data.append(DateModel(price: "23,500円" ))
        data.append(DateModel(price: "24,000円" ))
        data.append(DateModel(price: "24,500円" ))
        data.append(DateModel(price: "25,000円" ))
        data.append(DateModel(price: "25,500円" ))
        data.append(DateModel(price: "26,000円" ))
        data.append(DateModel(price: "26,500円" ))
        data.append(DateModel(price: "27,000円" ))
        data.append(DateModel(price: "27,500円" ))
        data.append(DateModel(price: "28,000円" ))
        data.append(DateModel(price: "28,500円" ))
        data.append(DateModel(price: "29,000円" ))
        data.append(DateModel(price: "29,500円" ))
        data.append(DateModel(price: "30,000円" ))
        data.append(DateModel(price: "30,500円" ))
        data.append(DateModel(price: "31,000円" ))
        data.append(DateModel(price: "31,500円" ))
        data.append(DateModel(price: "32,000円" ))
        data.append(DateModel(price: "32,500円" ))
        data.append(DateModel(price: "33,000円" ))
        data.append(DateModel(price: "33,500円" ))
        data.append(DateModel(price: "34,000円" ))
        data.append(DateModel(price: "34,500円" ))
        data.append(DateModel(price: "35,000円" ))
        data.append(DateModel(price: "35,500円" ))
        data.append(DateModel(price: "36,000円" ))
        data.append(DateModel(price: "36,500円" ))
        data.append(DateModel(price: "37,000円" ))
        data.append(DateModel(price: "37,500円" ))
        data.append(DateModel(price: "38,000円" ))
        data.append(DateModel(price: "38,500円" ))
        data.append(DateModel(price: "39,000円" ))
        data.append(DateModel(price: "39,500円" ))
        data.append(DateModel(price: "40,000円" ))
        data.append(DateModel(price: "40,500円" ))
        data.append(DateModel(price: "41,000円" ))
        data.append(DateModel(price: "41,500円" ))
        data.append(DateModel(price: "42,000円" ))
        data.append(DateModel(price: "42,500円" ))
        data.append(DateModel(price: "43,000円" ))
        data.append(DateModel(price: "43,500円" ))
        data.append(DateModel(price: "44,000円" ))
        data.append(DateModel(price: "44,500円" ))
        data.append(DateModel(price: "45,000円" ))
        data.append(DateModel(price: "45,500円" ))
        data.append(DateModel(price: "46,000円" ))
        data.append(DateModel(price: "46,500円" ))
        data.append(DateModel(price: "47,000円" ))
        data.append(DateModel(price: "47,500円" ))
        data.append(DateModel(price: "48,000円" ))
        data.append(DateModel(price: "48,500円" ))
        data.append(DateModel(price: "49,000円" ))
        data.append(DateModel(price: "49,500円" ))
        data.append(DateModel(price: "50,000円" ))
        data.append(DateModel(price: "50,500円" ))
        data.append(DateModel(price: "51,000円" ))
        data.append(DateModel(price: "51,500円" ))
        data.append(DateModel(price: "52,000円" ))
        data.append(DateModel(price: "52,500円" ))
        data.append(DateModel(price: "53,000円" ))
        data.append(DateModel(price: "53,500円" ))
        data.append(DateModel(price: "54,000円" ))
        data.append(DateModel(price: "54,500円" ))
        data.append(DateModel(price: "55,000円" ))
        data.append(DateModel(price: "55,500円" ))
        data.append(DateModel(price: "56,000円" ))
        data.append(DateModel(price: "56,500円" ))
        data.append(DateModel(price: "57,000円" ))
        data.append(DateModel(price: "57,500円" ))
        data.append(DateModel(price: "58,000円" ))
        data.append(DateModel(price: "58,500円" ))
        data.append(DateModel(price: "59,000円" ))
        data.append(DateModel(price: "59,500円" ))
        data.append(DateModel(price: "60,000円" ))
        data.append(DateModel(price: "60,500円" ))
        data.append(DateModel(price: "61,000円" ))
        data.append(DateModel(price: "61,500円" ))
        data.append(DateModel(price: "62,000円" ))
        data.append(DateModel(price: "62,500円" ))
        data.append(DateModel(price: "63,000円" ))
        data.append(DateModel(price: "63,500円" ))
        data.append(DateModel(price: "64,000円" ))
        data.append(DateModel(price: "64,500円" ))
        data.append(DateModel(price: "65,000円" ))
        data.append(DateModel(price: "65,500円" ))
        data.append(DateModel(price: "66,000円" ))
        data.append(DateModel(price: "66,500円" ))
        data.append(DateModel(price: "67,000円" ))
        data.append(DateModel(price: "67,500円" ))
        data.append(DateModel(price: "68,000円" ))
        data.append(DateModel(price: "68,500円" ))
        data.append(DateModel(price: "69,000円" ))
        data.append(DateModel(price: "69,500円" ))
        data.append(DateModel(price: "70,000円" ))
        data.append(DateModel(price: "70,500円" ))
        data.append(DateModel(price: "71,000円" ))
        data.append(DateModel(price: "71,500円" ))
        data.append(DateModel(price: "72,000円" ))
        data.append(DateModel(price: "72,500円" ))
        data.append(DateModel(price: "73,000円" ))
        data.append(DateModel(price: "73,500円" ))
        data.append(DateModel(price: "74,000円" ))
        data.append(DateModel(price: "74,500円" ))
        data.append(DateModel(price: "75,000円" ))
        data.append(DateModel(price: "75,500円" ))
        data.append(DateModel(price: "76,000円" ))
        data.append(DateModel(price: "76,500円" ))
        data.append(DateModel(price: "77,000円" ))
        data.append(DateModel(price: "77,500円" ))
        data.append(DateModel(price: "78,000円" ))
        data.append(DateModel(price: "78,500円" ))
        data.append(DateModel(price: "79,000円" ))
        data.append(DateModel(price: "79,500円" ))
        data.append(DateModel(price: "80,000円" ))
        data.append(DateModel(price: "80,500円" ))
        data.append(DateModel(price: "81,000円" ))
        data.append(DateModel(price: "81,500円" ))
        data.append(DateModel(price: "82,000円" ))
        data.append(DateModel(price: "82,500円" ))
        data.append(DateModel(price: "83,000円" ))
        data.append(DateModel(price: "83,500円" ))
        data.append(DateModel(price: "84,000円" ))
        data.append(DateModel(price: "84,500円" ))
        data.append(DateModel(price: "85,000円" ))
        data.append(DateModel(price: "85,500円" ))
        data.append(DateModel(price: "86,000円" ))
        data.append(DateModel(price: "86,500円" ))
        data.append(DateModel(price: "87,000円" ))
        data.append(DateModel(price: "87,500円" ))
        data.append(DateModel(price: "88,000円" ))
        data.append(DateModel(price: "88,500円" ))
        data.append(DateModel(price: "89,000円" ))
        data.append(DateModel(price: "89,500円" ))
        data.append(DateModel(price: "90,000円" ))
        data.append(DateModel(price: "90,500円" ))
        data.append(DateModel(price: "91,000円" ))
        data.append(DateModel(price: "91,500円" ))
        data.append(DateModel(price: "92,000円" ))
        data.append(DateModel(price: "92,500円" ))
        data.append(DateModel(price: "93,000円" ))
        data.append(DateModel(price: "93,500円" ))
        data.append(DateModel(price: "94,000円" ))
        data.append(DateModel(price: "94,500円" ))
        data.append(DateModel(price: "95,000円" ))
        data.append(DateModel(price: "95,500円" ))
        data.append(DateModel(price: "96,000円" ))
        data.append(DateModel(price: "96,500円" ))
        data.append(DateModel(price: "97,000円" ))
        data.append(DateModel(price: "97,500円" ))
        data.append(DateModel(price: "98,000円" ))
        data.append(DateModel(price: "98,500円" ))
        data.append(DateModel(price: "99,000円" ))
        data.append(DateModel(price: "99,500円" ))
    
        return data
    }

    

}
